"""
Copyright (C) 2021 Ilya "Faer" Gurov (ilya.faer@mail.ru)
License: https://github.com/IlyaFaer/ForwardOnlyGame/blob/master/LICENSE.md

Character and enemies classes definitions.
"""

CLASSES = {
    "male_soldier": {
        "health": 100,
        "energy_gain": 50,
        "energy_spend": 27,
        "healing": 22,
        "shots_num": 2,
        "shot_snd": "rifle_shot1",
    },
    "female_soldier": {
        "health": 80,
        "energy_gain": 40,
        "energy_spend": 27,
        "healing": 22,
        "shots_num": 2,
        "shot_snd": "rifle_shot1",
    },
    "male_raider": {
        "health": 100,
        "energy_gain": 35,
        "energy_spend": 21,
        "healing": 14,
        "shots_num": 1,
        "shot_snd": "shotgun_shot1",
    },
    "female_raider": {
        "health": 80,
        "energy_gain": 30,
        "energy_spend": 21,
        "healing": 14,
        "shots_num": 1,
        "shot_snd": "shotgun_shot1",
    },
    "male_anarchist": {
        "health": 100,
        "energy_gain": 50,
        "energy_spend": 27,
        "healing": 22,
        "shots_num": 3,
        "shot_snd": "pistol_shot1",
    },
    "female_anarchist": {
        "health": 80,
        "energy_gain": 40,
        "energy_spend": 27,
        "healing": 22,
        "shots_num": 2,
        "shot_snd": "pistol_shot1",
    },
}

NAMES = {
    "male": (
        "Aaron",
        "Adam",
        "Aidan",
        "Alex",
        "Alexis",
        "Antony",
        "Arnold",
        "Ben",
        "Bruce",
        "Chris",
        "Clint",
        "Cody",
        "Cory",
        "Craig",
        "Daren",
        "Donnie",
        "Ed",
        "Elijah",
        "Eric",
        "Felix",
        "Finn",
        "Frank",
        "Hans",
        "James",
        "Jerome",
        "Jordan",
        "Josh",
        "Justin",
        "Kenneth",
        "Lewis",
        "Mathew",
        "Max",
        "Mike",
        "Nathan",
        "Neill",
        "Paul",
        "Peter",
        "Philip",
        "Roy",
        "Shawn",
        "Sid",
        "Steven",
        "Tim",
        "Thomas",
        "Travis",
        "Tyler",
        "Werner",
    ),
    "female": (
        "Adriana",
        "Andrea",
        "Angelina",
        "Ann",
        "Barbara",
        "Casey",
        "Charlotte",
        "Christine",
        "Claudia",
        "Clara",
        "Cobie",
        "Dolores",
        "Elizabeth",
        "Emily",
        "Emma",
        "Eva",
        "Gillian",
        "Helena",
        "Isabela",
        "Jennifer",
        "Jessica",
        "Julia",
        "Karen",
        "Kate",
        "Laura",
        "Lea",
        "Luisa",
        "Maeve",
        "Megan",
        "Melissa",
        "Mia",
        "Miranda",
        "Monica",
        "Naomi",
        "Nele",
        "Olivia",
        "Paula",
        "Rachael",
        "Radha",
        "Rhonda",
        "Samara",
        "Sara",
        "Scarlett",
        "Sofia",
        "Stephanie",
        "Teresa",
        "Vanessa",
        "Victoria",
    ),
}
