"""
Copyright (C) 2020 Ilya "Faer" Gurov (ilya.faer@mail.ru)
License: https://github.com/IlyaFaer/ForwardOnlyGame/blob/master/LICENSE.md

Character and enemies classes definitions.
"""

CLASSES = {
    "male_soldier": {"health": 100, "energy_gain": 50, "energy_spend": 30},
    "female_soldier": {"health": 80, "energy_gain": 40, "energy_spend": 30},
    "male_raider": {"health": 100, "energy_gain": 35, "energy_spend": 23},
}

NAMES = {
    "male": (
        "Aaron",
        "Adam",
        "Alex",
        "Alexis",
        "Arnold",
        "Ben",
        "Bruce",
        "Chris",
        "Cody",
        "Cory",
        "Craig",
        "Donnie",
        "Ed",
        "Elijah",
        "Eric",
        "Frank",
        "James",
        "Jerome",
        "Jordan",
        "Josh",
        "Justin",
        "Lewis",
        "Mathew",
        "Max",
        "Mike",
        "Nathan",
        "Paul",
        "Peter",
        "Roy",
        "Shawn",
        "Sid",
        "Steven",
        "Tim",
        "Thomas",
        "Tyler",
    ),
    "female": (
        "Adriana",
        "Angelina",
        "Barbara",
        "Casey",
        "Charlotte",
        "Christine",
        "Dolores",
        "Elizabeth",
        "Emily",
        "Emma",
        "Eva",
        "Gillian",
        "Helena",
        "Isabela",
        "Jennifer",
        "Jessica",
        "Kate",
        "Laura",
        "Maeve",
        "Megan",
        "Melissa",
        "Mia",
        "Miranda",
        "Naomi",
        "Olivia",
        "Rachael",
        "Samara",
        "Sara",
        "Scarlett",
        "Sofia",
        "Stephanie",
        "Teresa",
        "Vanessa",
        "Victoria",
    ),
}
